# Generated by Django 2.2.3 on 2019-07-26 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barage',
            old_name='barage_conten',
            new_name='barage_content',
        ),
        migrations.RenameField(
            model_name='friends',
            old_name='frenid_id',
            new_name='friend_id',
        ),
        migrations.RenameField(
            model_name='friends',
            old_name='frenid_type',
            new_name='friend_type',
        ),
    ]
