# Generated by Django 2.2.3 on 2019-07-29 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20190729_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamics',
            name='create_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dynamics',
            name='update_at',
            field=models.DateTimeField(null=True),
        ),
    ]
