# Generated by Django 2.2.3 on 2019-07-29 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_auto_20190729_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odinaryusesr',
            name='user_id',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='odinaryusesr',
            name='user_password',
            field=models.CharField(max_length=256),
        ),
    ]
