# Generated by Django 2.2.3 on 2019-07-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_auto_20190729_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='odinaryusesr',
            name='code',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.DeleteModel(
            name='ConfirmString',
        ),
    ]
